language: node_js
node_js:
  - '0.10'
  - '0.11'

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: Ip+EQ3alYjHi+7t/dP1QlprKsoFSocykLObhfrm7u20aoQiz5VYH4Pdb9TGSl90G3BRo10dMF88jLStegiKcOAFaV1pARWCGnkNs5YaC3NeipJpvMM1HkkiL/p+ochragu/jxs2g4hGv77c8PXiaUaOjoQGqEGvOA00N48n7WCg=
  on:
    tags: true
    repo: tjwebb/sails-inject-models
    all_branches: true
